#!/bin/bash
if [[ ! $(whoami) == root ]]; then
    echo "Must be ran as root"
    exit 0
fi

# GET VALID MOUNTING DEVICES
mounted=$(lsblk --noheadings --raw -o NAME,MOUNTPOINT | awk '$1~/[[:digit:]]/ && $2~/\/mnt/ {print $2}')

#GET TABLE
unset DIRS
unset LINE
i=0
while read -r line; do
    crypt=$(lsblk -r | awk -v var="$line" '$7==var {print $6}')
    if [[ $crypt == crypt ]]; then
        continue
    fi
    ((i++))
    desc=$(lsblk -fr | sed 's/ /|/g' | awk -F"|" -v var="$line" '$7==var')
    dev=$(echo "$desc" | awk -F"|" '{print $1}')
    type=$(echo "$desc" | awk -F"|" '{print $2}')
    label=$(echo "$desc" | awk -F"|" '{print $3}')
    if [[ -z $label ]]; then
        label='-'
    fi
    dir=$(findmnt -r | column -t | awk -v var="$line" '$2==var {print $1}')
    if [[ -z $dir ]]; then
        dirdes=$(find $HOME/mnt -type l)
        dirsrc=$(echo "$dirdes" | xargs -I{} readlink {})
        dir=$(paste -d' ' <(echo "$dirsrc") <(echo "$dirdes") | grep "^$line" | awk '{print $2}')
    fi
    if [[ -z $DIRS ]]; then
        DIRS="$dir"
        LINE="$i $dev $type $label $line $dir"
    else
        DIRS=$(echo -e "$DIRS\n$dir\n")
        LINE=$(echo -e "$LINE\n$i $dev $type $label $line $dir")
    fi
done <<< "$mounted"

echo "TO UNMOUNT"
echo "$LINE" | column -t

# PROMPT
unset flag
while true; do

    if [[ -z flag ]]; then
        read -p "Which device?: " num
    else
        read -p "${ceol}Which device?: " num
    fi

    if [[ ! -z flag ]] && [[ $num -gt i ]] || [[ $num -lt 1 ]]; then
        tput cuu 2
        echo -e "\r${ceol}Invalid Response                               "
    elif [[ $num -gt i ]] || [[ $num -lt 1 ]]; then
        tput cuu 1
        echo -e "\r${ceol}Invalid Response                               "
    else
        break
    fi

    flag=1
done
dev1=$(echo "$LINE" | grep -e "^$num" | awk '{print $5}')
dev2=$(echo "$LINE" | grep -e "^$num" | awk '{print $6}')

echo ""
if [[ ! -z $(file "$dev2" | grep "symbolic link") ]]; then
    unlink "$dev2" && umount "$dev1"
else
    umount "$dev2" && umount "$dev1"
fi
echo ""
echo "done"
